pipeline {
  agent any
  stages {
    stage('Download dependencies') {
      steps {
        echo 'Download dependencies...'
        sh 'npm install'
      }
    }

    stage('Check linting') {
      steps {
        echo 'Check linting'
      }
    }

    stage('Tests') {
      steps {
        echo 'Test report'
        echo 'Test coverage'
      }
    }

    stage('Build') {
      steps {
        echo 'Build'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploy'
      }
    }
  }
}
