pipeline {
  agent any
  stages {
    stage('Загрузка зависимостей') {
      steps {
        echo 'Статический анализ кода'
        sh 'npm ci'
      }
    }

    stage('Статический анализ кода') {
      steps {
        echo 'Статический анализ кода'
      }
    }

    stage('Тесты') {
      steps {
        echo 'Test report'
        echo 'Test coverage'
      }
    }

    stage('Сборка проекта') {
      steps {
        echo 'Build'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploy'
      }
    }
  }
}
